name: Publish as Git Book on GitHub Pages
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "main"
    paths:
      - "resources/**"
      - "mkdocs.yml"
      - "requirements.txt"

jobs:
  deploy_docs:
    name: Deploy docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}